### ISSUE TITLE
Ellipsis anywhere in message breaks sends you to an error page

### ISSUE THREAD

**Issue by tbremer** [grotewold/love-airbnb#2]
Dear, Message, or Sender with an ellipsis routes you to `/ad` with an `Internal Server Error` message.

Side note: This is real neat! :beers:

**Comment by grotewold** [comment]
Make that all Unicode characters... :frown: ok I got this soon!

Thanks for the support!!

**Comment by grotewold** [comment]
With 337ef087301f8bf9d0f395c336e6ba720fbf0159, common unicode characters are supported, but it's all dependent on the font... currently not a ton of characters in my file. Thanks again!
